name: fruit_app
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  equatable: ^2.0.5
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.1

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  get: ^4.6.5
  ficonsax: ^0.0.3
  animated_bottom_navigation_bar: ^1.3.3
  get_storage: ^2.1.1
  dio: 5.4.0
  smooth_page_indicator: ^1.1.0
  flutter_animated_icon_button: ^1.1.3
  flutter_native_splash: ^2.3.10
  intl: ^0.18.1
  logger: ^2.0.1

  url_launcher: ^6.1.12
  carousel_slider: 4.2.1


dev_dependencies:
  test: ^1.24.9
  http_mock_adapter: ^0.6.1
  mockito: ^5.4.4
  flutter_test:
    sdk: flutter

     
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true


  assets:
    - assets/images/onboarding/
    - lib/features/home/data/productdata.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
